Add Startuplist Africa
PaystackHQ/nigerialogos pull request #150
Opened 2020-09-06 07:54 UTC by youngbobby

Added **Startuplist Africa** – a data-driven platform for discovering and gaining insight into African Startups

2020-09-07 08:59 UTC, demilad requested changes
Nice @youngbobby 
Change your file names to be separated by an underscore `_` and not a dash `-` as specified in the [contributing](https://github.com/PaystackHQ/nigerialogos/blob/master/contributing.md) document.

Also undo your style formatting of the `logos.json` file so it's easier to see the new changes you're actually adding to the file

2020-09-08 07:16 UTC, youngbobby commented
Fixed.

2020-09-08 07:29 UTC, demilad submitted a review, later dismissed

2020-11-27 15:11 UTC, demilad approved these changes

2020-11-27 15:11 UTC, merged