Added Tix Africa Logo and Details
PaystackHQ/nigerialogos pull request #156
Opened 2021-01-24 16:37 UTC by charlesochei

# Pull Request Contains

* Tix Africa Logo (PNG & SVG)
* Tix Africa's Details (logo.json)
* New Category `Event Management`

2021-01-25 08:02 UTC, demilad requested changes
Nice @charlesochei  
Looks like there's some more room for optimisation here.

Ensure your SVG & PNG logos have been properly optimised with tools like [SVGOMG](https://jakearchibald.github.io/svgomg/) & [Squoosh](https://squoosh.app/) (OxiPNG works well) respectively

2021-01-25 08:57 UTC, charlesochei commented
Hello, @demilad thanks for the feedback. I have optimized the images. Could you help me update or merge this? I don't know how to. A developer helped me made this pull request and he not available right now to help me update this PR. 
Here's a drive link to the optimized images: https://drive.google.com/drive/folders/1VSkl6HHIsqRC2CCwKSYXUr28-NQrjfWV?usp=sharing. I'd appreciate if you help me update the images in the PR.

2021-01-25 10:38 UTC, demilad approved these changes

2021-01-29 07:17 UTC, charlesochei commented
Hello @demilad, this PR is yet to be merged. It's been four days now. Could please reach out to @Odusanya on my behalf to review and merge the PR? I'd really appreciate it. Thanks.

2021-01-29 08:54 UTC, merged