Peerstack
PaystackHQ/nigerialogos pull request #172
Opened 2021-04-25 22:14 UTC by ichtrojan

2021-04-26 08:11 UTC, demilad requested changes
Nice @ichtrojan 
Ensure your logos have been properly optimised with tools like:
    [SVGOMG](https://jakearchibald.github.io/svgomg/) &
    [Squoosh](https://squoosh.app/) **(OxiPNG works well)**.

2021-04-26 09:01 UTC, ichtrojan commented
Thanks @demilad, 

Done, this is actually the smallest they could be compressed to.

2021-04-26 09:14 UTC, demilad approved these changes

2021-04-26 19:20 UTC, demilad approved these changes

2021-04-27 08:37 UTC, Odusanya approved these changes

2021-04-27 08:37 UTC, merged