Pushed 3 Companies
PaystackHQ/nigerialogos pull request #176
Opened 2021-06-19 17:24 UTC by prezine

1. Circlepanda (circlepanda.io)
2. Pandascrow (pandascrow.io)
3. Farmsby (farmsby.com)

2021-06-21 09:57 UTC, demilad submitted a review, later dismissed

2021-07-29 17:31 UTC, Odusanya requested changes

2021-07-29 17:31 UTC, Odusanya commented on logos/farmsby/farmsby.svg
> +<g clip-path="url(#clip0)">
Nice @prezine
Looks like there's some more room for optimisation here.

Ensure your SVG & PNG logos have been properly optimised with tools like [SVGOMG](https://jakearchibald.github.io/svgomg/) & [Squoosh](https://squoosh.app/) (OxiPNG works well) respectively

2021-07-29 17:31 UTC, Odusanya commented on logos/pandascrow/pandascrow.svg
> +<path fill-rule="evenodd" clip-rule="evenodd" d="M0 8.5C0 11.846 1.93331 14.7404 4.7438 16.1271C2.98661 19.7103 2 23.7399 2 28C2 42.2226 12.9969 53.8768 26.9518 54.9235C26.9496 54.9158 26.949 54.908
Nice @prezine
Looks like there's some more room for optimisation here.

Ensure your SVG & PNG logos have been properly optimised with tools like [SVGOMG](https://jakearchibald.github.io/svgomg/) & [Squoosh](https://squoosh.app/) (OxiPNG works well) respectively

2021-08-04 09:53 UTC, prezine commented
SVG's have been optimized, can it be looked into? 
Cheers

2021-09-09 09:09 UTC, Odusanya approved these changes

2021-09-09 09:09 UTC, merged