Add TalentQL
PaystackHQ/nigerialogos pull request #180
Opened 2021-09-08 17:49 UTC by John-pels

2021-09-08 17:54 UTC, demilad requested changes
Nice @John-pels 
Looks like there's some more room for optimisation here.

Ensure your SVG & PNG logos have been properly optimised with tools like [SVGOMG](https://jakearchibald.github.io/svgomg/) & [Squoosh](https://squoosh.app/) (OxiPNG works well) respectively

2021-09-08 18:27 UTC, John-pels commented
@demilad I have optimised the SVG file.

2021-09-08 18:59 UTC, demilad approved these changes

2021-09-09 09:07 UTC, Odusanya approved these changes

2021-09-09 09:07 UTC, merged