Update eyowo logo
PaystackHQ/nigerialogos pull request #188
Opened 2021-11-18 15:49 UTC by shaolinmkz

- Update the Eyowo SVG file
- Update the Eyowo PNG file

2021-11-19 11:21 UTC, demilad requested changes
Nice @shaolinmkz 
Looks like there's a little more room for optimisation on the Eyowo SVG. 
You can use [SVGOMG](https://jakearchibald.github.io/svgomg/) for that

2021-11-19 21:00 UTC, shaolinmkz commented
Thanks @demilad 
I actually used SVGOMG and that was the best it could give me...
I just tried optimizing it again and the output was still 4kb, although on the UI it shows `1.91k → 1.73k 90.46%` but the output remains 4kb after download.

<img width="1395" alt="Screenshot 2021-11-19 at 9 56 09 PM" src="https://user-images.githubusercontent.com/38951888/142690996-66e73263-7c00-4938-b49f-ce79c39e5764.png">

2022-06-21 07:57 UTC, Odusanya approved these changes

2022-06-21 14:49 UTC, demilad approved these changes

2022-08-19 01:03 UTC, merged