Adding Yournotify
PaystackHQ/nigerialogos pull request #190
Opened 2021-11-21 02:01 UTC by charlesmudy

2021-11-24 10:03 UTC, demilad requested changes
Hey @charlesmudy 
Looks like there's some more room for optimisation here.

Ensure your SVG & PNG logos have been properly optimised with tools like [SVGOMG](https://jakearchibald.github.io/svgomg/) & [Squoosh](https://squoosh.app/) (OxiPNG works well) respectively

2021-11-25 07:31 UTC, charlesmudy commented
@demilad ... I just pushed and updated version from the link you shared!

2021-11-25 08:58 UTC, demilad approved these changes

2022-06-21 07:37 UTC, Odusanya approved these changes

2022-06-21 07:38 UTC, merged