Sendchamp logo
PaystackHQ/nigerialogos pull request #220
Opened 2022-06-10 21:20 UTC by surmount96

2022-08-02 21:04 UTC, demilad requested changes
Nice @surmount96 

Looks like there's a little more room for optimising the SVG file here.
Please ensure your files have been optimised using tools like: [SVGOMG](https://jakearchibald.github.io/svgomg/) & [Squoosh](https://squoosh.app/) (OxiPNG works well)

2022-08-29 21:53 UTC, surmount96 commented
The svg file has been optimized

2022-08-30 01:23 UTC, demilad approved these changes

2022-10-18 08:21 UTC, Odusanya approved these changes

2022-10-18 08:22 UTC, merged